name: anywash_delivery
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.2+3

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter


  cupertino_icons: ^1.0.3
  country_code_picker: ^2.0.1
  flutter_bloc: ^7.0.0
  flutter_phoenix: ^1.0.0
  flutter_rating_bar: ^4.0.0
  shared_preferences: ^2.0.5
  animation_wrappers : ^0.0.4
  google_mobile_ads: ^0.13.2
  google_maps_flutter: ^2.0.6
  flutter_polyline_points: ^1.0.0
  equatable: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.9.0"



flutter_launcher_name:
  name: "Any Wash Delivery"

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/appIcon.png"

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/Icons/
    - assets/address/
    - assets/Services/
    - assets/Stores/
    - assets/FooterMenu/
    - assets/Account/
    - assets/Items/
    - assets/PaymentOptions/
    - assets/TrackingIcons/
    - assets/Maps/

  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins/Poppins-Bold.ttf
        - asset: fonts/Poppins/Poppins-BoldItalic.ttf
        - asset: fonts/Poppins/Poppins-Light.ttf
        - asset: fonts/Poppins/Poppins-LightItalic.ttf
        - asset: fonts/Poppins/Poppins-Medium.ttf
        - asset: fonts/Poppins/Poppins-MediumItalic.ttf
        - asset: fonts/Poppins/Poppins-Regular.ttf
        - asset: fonts/Poppins/Poppins-Thin.ttf



